### ISSUE TITLE
/matches/:id/games = 戦ごとの戦績一覧ページ

### ISSUE THREAD

**Issue by arsley** [arsley/yakuman#8]
## 背景

`/games` で全体成績を見れる必要はそんなになくて、個別の戦でどのくらいの戦績か見れるほうが良い。

## 案

- [ ] `/matches/games.vue` を作る? (`:id` を伴う場合のページ生成について調べる)

**Comment by tj16kimura** [comment]
Vueもパスパラメータとクエリパラメータでイケるはず

**Comment by arsley** [comment]
多分これで caeec9fbc53014b8cff8e96f40d8dd20e650329b 実現した。
